package com.ui.enums;

public enum ConfigProperties {
    URL,
    BROWSER_NAME,
    BROWSER_VERSION,
    LAMBDA_HUB_URL,
    GRID_HUB_URL,
    HEADLESS,
    INCOGNITO,
    REMOTE,
    OVERRIDEREPORTS,

    MAXIMUM_NUMBER_OF_ATTEMPTS,
    PASSEDSTEPSSCREENSHOTS,
    FAILEDSTEPSSCREENSHOTS,
    SKIPPEDSTEPSSCREENSHOTS
}